image: gitpod/workspace-full:latest

tasks:
  - name: Android SDK and Flutter Setup
    init: |
      echo 'Setting up Java...'
      sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
      echo 'export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.bashrc
      echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      echo 'Done setting up Java.'
      
      echo 'Setting up Android SDK...'
      wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      mkdir -p /workspace/android-sdk/cmdline-tools
      unzip commandlinetools-linux-11076708_latest.zip -d /workspace/android-sdk/cmdline-tools
      rm commandlinetools-linux-11076708_latest.zip
      echo 'export ANDROID_SDK_ROOT="/workspace/android-sdk"' >> ~/.bashrc
      echo 'export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/bin:$ANDROID_SDK_ROOT/platform-tools"' >> ~/.bashrc
      source ~/.bashrc && yes | sdkmanager --licenses && sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"
      echo 'Done setting up Android SDK.'
      
      echo 'Setting up Flutter...'
      wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.5-stable.tar.xz
      tar xf flutter_linux_3.19.5-stable.tar.xz -C /workspace
      rm flutter_linux_3.19.5-stable.tar.xz
      echo 'export PATH="/workspace/flutter/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc && flutter config --android-sdk "$ANDROID_SDK_ROOT"
      echo 'Done setting up Flutter.'
      
    command: |
      echo 'Starting Flutter doctor...'
      source ~/.bashrc && flutter doctor

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.flutter
    - Dart-Code.dart-code
